### ISSUE TITLE
broken NFDI link

### ISSUE THREAD

**Issue by cpauvert** [FelixHenninger/cookiecutter#1]
Hi @FelixHenninger,
I stumble upon your package (looking forward to try it out!) and realized that the link to your NFDI was probably broken. The culprit is probably here: 
https://github.com/FelixHenninger/cookiecutter/blob/3d25c1fcf0d061f8d2456e21e2a90858fa201fa5/pkgdown/_pkgdown.yml#L7

It seems the https://www.berd-nfdi.de/ link works though.

Best,

**Comment by FelixHenninger** [comment]
Dear @cpauvert, many thanks for catching this and letting us know! Indeed I had totally missed testing that link. I've fixed it, and improved the label also, in f133787. 

Thanks again for your kind message, and please let us know if you have any more feedback, I'd be all ears. Kind regards, and happy holidays,


-Felix

**Comment by cpauvert** [comment]
No problem! Happy to help :  )
